{% set version = "0.1.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-chemometricswithr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ChemometricsWithR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ChemometricsWithR/ChemometricsWithR_{{ version }}.tar.gz
  sha256: f852f6f04d7404d6e0ed552318e5809465bdc0bf9cf03a71109b873a5e50db98

build:
  noarch: generic
  number: 5
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-mass
    - r-devtools
    - r-kohonen
    - r-pls
  run:
    - r-base
    - r-mass
    - r-devtools
    - r-kohonen
    - r-pls

test:
  commands:
    - $R -e "library('ChemometricsWithR')"           # [not win]
    - "\"%R%\" -e \"library('ChemometricsWithR')\""  # [win]

about:
  home: https://github.com/rwehrens/CWR
  license: GPL (>= 2)
  summary: Functions and scripts used in the book "Chemometrics with R - Multivariate Data Analysis
    in the Natural Sciences and Life Sciences" by Ron Wehrens, Springer (2011). Data
    used in the package are available from github.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
